name: Deploy Staging Build

on:
  push:
    branches: [ 'releases/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create tag
        uses: actions/github-script@v7
        id: create-tag
        with:
          script: |
            echo 'VERSION_NAME=${GITHUB_REF##*/}'
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{env.VERSION_NAME}}',
              sha: context.sha
            })
        
     # - name: Setup Environment
     #   uses: ./.github/actions/setup-environment

     # - name: Build Debug APK
     #   run: ./gradlew assembleStagingRelease
