name: Deploy Staging Build

on:
  push:
    branches: [ 'releases/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set env
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/}" >> $GITHUB_ENV
      
      - name: Test
        run: echo $REPOSITORY_NAME
        
     # - name: Setup Environment
     #   uses: ./.github/actions/setup-environment

     # - name: Build Debug APK
     #   run: ./gradlew assembleStagingRelease
