name: Deploy Staging Build

on:
  push:
    branches: [ 'releases/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Release Version
        run: echo "VERSION_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v7
        id: create-tag
        env:
          VERSION_NAME: 'refs/tags/${{env.VERSION_NAME}}'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{env.VERSION_NAME}}',
              sha: context.sha
            })
        
     # - name: Setup Environment
     #   uses: ./.github/actions/setup-environment

     # - name: Build Debug APK
     #   run: ./gradlew assembleStagingRelease
