name: Deploy Staging Build

on:
  push:
    branches: [ 'releases/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: $BRANCH_NAME
      
        
     # - name: Setup Environment
     #   uses: ./.github/actions/setup-environment

     # - name: Build Debug APK
     #   run: ./gradlew assembleStagingRelease
