name: Deploy Staging Build

on:
  push:
    branches: [ 'releases/**' ]

permissions:
  actions: write
  contents: write
  deployments: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Release Version
        run: echo ${{ github.workspace }}
        
     # - name: Setup Environment
     #   uses: ./.github/actions/setup-environment

     # - name: Build Debug APK
     #   run: ./gradlew assembleStagingRelease
