name: Perform PR Check

on:
  push:
    branches: [ main, develop, 'releases/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build with Gradle
        run: ./gradlew build

